# Generated by Django 3.2.4 on 2021-08-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatela', '0002_campanamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonadorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('cantidad_donada', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
