# Generated by Django 3.2.4 on 2021-09-07 22:59

from django.db import migrations, models
import donatela.enums


class Migration(migrations.Migration):

    dependencies = [
        ('donatela', '0004_campanamodel_donadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanamodel',
            name='descripcion_completa',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campanamodel',
            name='estado_campana',
            field=models.CharField(choices=[(donatela.enums.EstadoCampana['ACTIVA'], 'Activa'), (donatela.enums.EstadoCampana['FINALIZADA'], 'Finalizada')], default='Activa', max_length=10),
        ),
    ]
