# Generated by Django 3.2.4 on 2021-09-08 01:31

from django.db import migrations, models
import donatela.enums


class Migration(migrations.Migration):

    dependencies = [
        ('donatela', '0005_auto_20210907_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanamodel',
            name='descripcion_completa',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campanamodel',
            name='estado_campana',
            field=models.CharField(choices=[(donatela.enums.EstadoCampana['ACTIVA'], 'Activa'), (donatela.enums.EstadoCampana['FINALIZADA'], 'Finalizada')], max_length=10),
        ),
        migrations.AlterField(
            model_name='campanamodel',
            name='url_imagen',
            field=models.CharField(max_length=1000),
        ),
    ]
