# Generated by Django 3.2.4 on 2021-09-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatela', '0006_auto_20210907_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanamodel',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
