# Generated by Django 3.2.4 on 2021-09-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatela', '0007_alter_campanamodel_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanamodel',
            name='recaudacion_esperada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
